---
# configuration file of durl, which is a CLI tool to check whether dead urls are included in files.
# https://github.com/suzuki-shunsuke/durl
ignore_urls:
- https://codecov.io/bash  # sometimes returns 503
ignore_hosts:
- goreportcard.com
http_method: head,get
max_failed_request_count: -1
