---
version: 2
jobs:
  build:
    docker:
    - image: suzukishunsuke/go-ci:0.1.0-0
    working_directory: /go/src/github.com/suzuki-shunsuke/go-set
    steps:
    - checkout
    - run: npm i
    # commitlint
    - run: bash script/commitlint-circleci.sh
    # gometalinter
    - run: npm run lint
    # go test
    - run: bash script/coverage.sh
    # upload codecov
    - run: bash <(curl -s https://codecov.io/bash)
    environment:
      GO111MODULE: on
